<?php
    function cookies_analytics_block_info(){
        $blocks['id-cookie'] = array{
            'info' => t('Cookie'),
        };
        return $blocks;
    }
    function cookies_analytics_block_view($delta == ''){
        $block = array();
        switch{$delta}{
            case 'id-cookie':
                $block['content'] = cookie();
        }
        return $block;
    }
    function cookie(){
        return '<h2>'.t('Cookie Test')'</h2>';
    }
