<?php
  function cookies_analytics_block_info() {
    $blocks = array();
  
    // Define el bloque de popup.
    $blocks['cookies_analytics'] = array(
      'info' => t('Cookie Analytics'),
      'cache' => DRUPAL_NO_CACHE, // Evita el caché del bloque.
    );
  
    return $blocks;
  }
  
  /**
   * Implementa hook_block_view().
   */
  function cookies_analytics_block_view($delta = '') {
    $block = array();
  
    if ($delta == 'cookies_analytics') {
      // Verifica si es la primera visita del usuario mediante una cookie.
      if (!isset($_COOKIE['cookies_analytics_visited'])) {
        // Carga la librería de jQuery UI.
        drupal_add_library('system', 'ui.dialog');
  
        // Agrega el CSS y el JS para mostrar el popup de bienvenida.
        drupal_add_css(drupal_get_path('module', 'cookies_analytics') . '/css/popup.css');
        drupal_add_js(drupal_get_path('module', 'cookies_analytics') . '/js/popup.js');
  
        // Crea el contenido del popup de bienvenida.
        $popup_content = '<div id="cookie_analytics_popup" class="cookiesjsr-banner active">' .
                          '<div class="cookiesjsr-banner--content">' .
                            '<div class="cookiesjsr-banner--info">' .
                              '<span class="cookiesjsr-banner--text">Esta página web utiliza cookies para analizar el uso que usted hace de la web, de forma anónima y estadística, con la finalidad de mejorar los contenidos y su experiencia de navegación. Para más información accede a la Política de Cookies</span>' .
                              '<ul class="cookiesjsr-links">' .
                                '<li><a href="https://utpl.edu.ec/sites/default/files/normativasweb/Politicas_cookies.pdf" target="_blank" rel="noopener noreferrer">Política de Cookies</a></li>' .
                              '</ul>' .
                            '</div>' .
                            '<div class="cookiesjsr-banner--action">' .
                              '<button class="cookiesjsr-btn cookiesjsr-settings">CONFIGURACIÓN DE COOKIES</button>' .
                              '<button class="cookiesjsr-btn important denyAll">DENEGAR TODO</button>' .
                              '<button id="cookie_analytics_aceptar_btn" class="cookiesjsr-btn important allowAll">ACEPTAR TODO</button>' .
                            '</div>' .
                          '</div>' .
                        '</div>';
  
        $block['content'] = $popup_content;
      }
    }
  
    return $block;
  }
  
  /**
   * Implementa hook_menu().
   */
  function cookies_analytics_menu() {
    $items = array();
  
    // Ruta para almacenar la visita del usuario mediante Ajax.
    $items['cookies-analytics/aceptar'] = array(
      'page callback' => 'cookies_analytics_aceptar',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    );
  
    return $items;
  }
  
  /**
   * Callback para almacenar la visita del usuario mediante Ajax.
   */
  function cookies_analytics_visited() {
    // Establece una cookie para recordar la visita del usuario.
    setcookie('cookies_analytics_visited', 'true', time() + (365 * 24 * 60 * 60), '/');
    return '';
  }